---
- hosts: all

  tasks:
    - include_tasks: packages.yml
      tags: ["packages"]
    - include_tasks: user.yml
    - include_tasks: python.yml
      tags: ["app"]
    - include_tasks: files.yml
      tags: ["files"]
    - include_tasks: database.yml
      tags: ["database"]
    - include_tasks: django.yml
      tags: ["django"]
    - include_tasks: services.yml
      tags: ["services"]
