name: Auto release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubunut-latest

    steps:
      - name: Generate automatic release
        uses: actions/create-release@v1
        with:
          release_name: New release
          body: Release generada automaticamente
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


